### ISSUE TITLE
Isolate the 5V power supply

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opqbox2#15]
Richard Westlake comments that the current design with an unisolated power supply creates a safety risk in the presence of high voltage transients. His suggestions include:

  * Use a DC-DC Converter operated from the 5V supply out of the Mean Well module.

  * A partial re-layout will be required.

  * There are several Murata SIP 7 parts that will do the task.  I've used them in high power circuits for motor controls, plasma  cutters, and magnetizers to power isolated gate drivers and current sensors. I prefer the 5.2 KVV parts such as the NMJ0505SAC ( ~ $14 )

  * If your safety standard can tolerate a lower isolation voltage then the 3KV parts such as the MEV0505SC ( ~ $8 ) should be OK for a 120 Vac line isolation.

  * The [Digikey page showing DC-DC converters](http://www.digikey.com/product-search/en?pv597=57&pv597=48&pv597=50&FV=fff40042%2Cfff800df%2Cfffc01ea%2Cfffc032b%2C15c0002%2C2dc0202%2C2dc1bff%2C8f40015%2C8f40025%2C8f4002f%2C16fc0009%2C16fc000b%2C16fc0014%2C16fc0022%2C17000001%2C17d4003e&k=dc-dc+converters&mnonly=0&newproducts=0&ColumnSort=0&page=1&quantity=0&ptm=0&fid=0&pageSize=25)

  * You may need to add some external filter capacitors to clean-up the output switching noise.

  * Probably a 10uF || 0.1uF X7R , 10uHy , 10uF || 0.1 X7R   Pi filter will make it plenty clean enough to not upset the input to the isolation amplifiers.

  * Try it ... you may not need the inductor ... since the power supply rejection of the AMC1100 is very good.

**Comment by philipmjohnson** [comment]
(Also from Richard)

In terms of getting an isolated supply for the front end with minimum power loss ... I found another device that is lower power than the Murata dc-dc converters.
It's the Analog Devices ADUM5000
http://www.analog.com/en/products/interface-isolation/isolation/standard-digital-isolators/adum5000.html#product-overview

**Comment by philipmjohnson** [comment]
(Adding more info from Richard)
This type of approach is better than the capacitor input circuit and will be more efficient.

http://www.mouser.com/ds/2/149/FSAR001B-112572.pdf

Will the MOV being used keep any transients below the breakdown voltage of the device ?

What transient voltage and source impedance are you designing for ?

The Mean Well  IRM-10-5 and -12 modules are only specified to withstand a 1KV transient event.

---------------

The Fairchild part is similar to and uses fewer parts than some Supertex parts ... like the SR086.

 http://www.microchip.com/ParamChartSearch/Chart.aspx?branchID=90251

 ---------------

 Will this give us the needed supply hold-up during extreme low line events ?

 Will we be able to capture 'bad' transients near the shutdown and re-start of short power line dropouts ?

-------------------

 Another way of getting an isolated supply for the front end is to run it from the 5V supply ... I found a device that is lower power than the Murata dc-dc converters.

 It's the Analog Devices ADUM5000

 http://www.analog.com/en/products/interface-isolation/isolation/standard-digital-isolators/adum5000.html#product-overview

 In a similar bad power environment I've previously used a 12V power module with a large output capacitor ( 5000 uF ) followed by a simple 5V switcher from Linear Technology.

 That way the 12 V supply will discharge down to about 5.5 V and the 5V output will stay in regulation.

By using a device like this we can have the 5V supply hold-up for low line voltage events lasting for many power line cycles or perhaps many seconds.

--------------------

 ( We get those on-off-on-off-on events here ... typically during the winter months.  I've lost several computer and switching wall knocker power supplies to those events.)

 So my opinion is that we need to capture that type of event ... to see the magnitudes of the voltage excursions ...

and of course the choice is yours.

**Comment by sergey-negrashov** [comment]
Prototype using the ADUM5010 has been assembled and is undergoing testing. The layout and schematics are committed in 014b97cdd404a07f0a5ac01ad611f8c5de5e6673. Additionally a 0.22uF super-capacitor circuit has been added to the 5V rail. Device has been manufactured and is undergoing testing.

**Comment by sergey-negrashov** [comment]
As of 2.7 ADUM5010 is a standard way to power the hot side measurements. This has an added benefit of giving us a centralized power entry for battery power on the isolated side.
