### ISSUE TITLE
Monitor both line-to-neutral and neutral-to-ground

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opqbox2#18]
Every single-phase power quality monitor since at least the mid-1970's monitors both line-to-neutral and neutral-to-ground.  There's a lot of local information in the neutral-to-ground measurements.  It's perfectly acceptable to monitor Line-to-Ground, and Neutral-to-Ground, then digitally calculate the sample-by-sample difference to get a Line-to-Neutral value.  (Do think about what happens when Line and Neutral are reversed -- they often are -- or what happens when ground is missing -- it often is. In particular, pay attention to earth currents caused by your attenuators...)  (From Alex)

**Comment by sergey-negrashov** [comment]
I would really like to measure E to N. Maybe in V3
