### ISSUE TITLE
Support single-fault condition testing

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opqbox2#22]
You'll find that the UL standard requires testing in the "single-fault condition".  As a practical matter, this means that during the test, they will either short-circuit or remove (whichever is worse) a single component, and your design must continue to operate safely.  So what happens when R5 is shorted? R4 will draw 120 mA, which is not enough current to blow the fuse.  Maybe R4 needs to be a 20-watt resistor? Or is there another solution?  (From Alex)

**Comment by sergey-negrashov** [comment]
Added a 0.1A fuse on the measurement side, along with a TVS it will protect from the divider failure.
