### ISSUE TITLE
Provide balanced attenuator

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opqbox2#23]
It would be more conventional to have a balanced attenuator, i.e. half the attenuation on Line, half on Neutral -- you'll do this when you add the neutral-to-earth channel, anyway, and it solves 4d in a way, right?  Well, maybe not. Think about what happens when the R5 is shorted on the Line side, and the Neutral side is very close to earth.  (From Alex)

**Comment by sergey-negrashov** [comment]
If we ever get to V3 I would really like to measure DC(N-E) but its just not feasible with this design.
