### ISSUE TITLE
Characterize attenuator frequency response

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opqbox2#25]
What's the equivalent capacitance of TVS2? How does that work with R5's ~1Megohm resistance? What effect does that combination have on the frequency response of the attenuator? If the 3dB point is lower than a few hundred kHz, how will you measure 2kHz-150kHz emissions?  (From Alex)

**Comment by sergey-negrashov** [comment]
SMBJ7.0 Is not the right part to use here, however there are plenty of TVS diodes with ~2.5pF junction capacitance which would give us a 3dB point of ~60hHz. Very good point.
