### ISSUE TITLE
Ensure AD7684 has sufficient anti-alias filter

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opqbox2#26]
Where is the analog anti-alias filter for the aD7684? The single-pole of R28/R29/C29 is probably too simple for this application, because there's going to be so much noise/signal just above the F/2 sampling frequency. Typically, 3-pole or 4-pole analog filters are used on each channel, followed by digital filters implemented in the DSP.   (From Alex)

**Comment by sergey-negrashov** [comment]
Won't fix for V2. Need some more analog expertise. Digital filter is under development.
