### ISSUE TITLE
Charge supercapacitor through constant-current circuit

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opqbox2#27]
The text and schematic refer to a 0.22uF super capacitor -- I assume this is actually a 0.22F (not uF) super capacitor?  The resistor charge circuit will require -- at 3 time constants -- about 20 seconds to charge.  And only the 1.3 volts between 5V and 3.7V is useful, given the AP2120 regulator - the rest of the storage is wasted.  You mention about 1 second of operating time on the super capacitor, so I assume you've got about 220 mA of load - is that right?  It does seem a pity to charge through a resistor, instead of a constant-current circuit, given that the useful power is all at the top end of the voltage where the charging is slowest.  (From Alex)

**Comment by sergey-negrashov** [comment]
Droped the supercap in favor of a DCDC and a LIFEPO4
