### ISSUE TITLE
Assess impact of fuse on monitor operating range

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opqbox2#29]
F1, the fuse, probably needs some very careful calculations - I wasn't comfortable with what I saw.  In an "ordinary" electronic device, it's OK for the fuse to blow when there's a big power disturbance, but not in a PQ monitor.  After all, the whole point of a PQ monitor is to keep operating no matter what happens on the power line, especially if it's something bad!  (From Alex)

**Comment by philipmjohnson** [comment]
1A is required to handle in-rush current; not sure if our device can continue to run under more extreme conditions. Will look further.

**Comment by sergey-negrashov** [comment]
We are now fusing both the measurement and the power. The fuse should have very minimal impact. Since the input impedance of our analog front end is ~1M, so any fuse contribution is negligible .
