### ISSUE TITLE
GPS antennas and lightning strikes

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opqbox2#30]
Where's the time reference that's sufficiently stable to meet the requirements in the Standard?  GPS is an obvious choice, but be careful - you can't bring the GPS antenna cable inside the house.  That's acceptable in a lot of applications, but in a PQ monitor you've got to assume lightning strikes; and the braided shield on the GPS antenna cable provides a great path for lightning, especially if it's anywhere close to earth potential inside the house.   (From Alex)

**Comment by philipmjohnson** [comment]
Time synchronization is currently an active design issue that we are working on.  We do not expect to have GPS on all devices.

**Comment by sergey-negrashov** [comment]
I think this is largely outside of scope of our device. It would be trivial to add the path to earth for the GPS antenna, but the GPS module is not a part of the PCB
